// Logout
export const LOGIN = 'LOGIN';
export const USER_SIGNUP_REQUESTED = 'USER_SIGNUP_REQUESTED';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const LOGOUT = 'LOGOUT';

// App::Theme
export const THEME = 'THEME';
export const STORAGE_KEY = 'THEME_ID';

// App::InternetConnectionChange
export const CONNECTION_STATE_CHANGED = 'CONNECTION_STATE_CHANGED';

// App::Loader
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_LOADER = 'SHOW_LOADER';

// App::Login
export const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA';
export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';


//Feeds
export const GETITEMS_REQUESTED = 'GETITEMS_REQUESTED';
export const GETITEMS_SUCCESS = 'GETITEMS_SUCCESS';

export const SEARCHITEMS_REQUESTED = 'SEARCHITEMS_REQUESTED';
export const SEARCHITEMS_SUCCESS = 'SEARCHITEMS_SUCCESS';


//Activity
export const ACTIVITY_REQUESTED = 'ACTIVITY_REQUESTED';
export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_DATA = 'UPDATE_ACTIVITY_DATA';
export const LOADMOREACTIVITY_REQUESTED = 'LOADMOREACTIVITY_REQUESTED'
export const LOADMOREACTIVITY_SUCCESS = 'LOADMOREACTIVITY_SUCCESS'

